### PR TITLE
fix(materials): inputs-values-tree display bug

### LINKED ISSUE #691: [Bug] InputsValuesTree Object type field will be reset after drilling down
## 🙋 SDK Version
0.4.1

## 📌 Layout
Free layout 

## 💻 Environment
- Operation System: (e.g. Windows 10 )
- Node.js: 18.20.8
- Other:

## 📝 Question Description

https://github.com/user-attachments/assets/c31caa4a-ed74-4bcd-8691-e52507d9273e

### PR DESCRIPTION
**Pull request by sanmaopep**
Fix #691

### CODE REVIEW

File: packages/materials/form-materials/src/components/inputs-values-tree/row.tsx [hunk 1]
```diff
@@ -64,14 +65,28 @@ export function InputValueRow(
...
+        ? ({
+            type: 'constant',
+            schema: { type: 'object' },
+          } as IFlowConstantValue)
+        : value,
+    [hasChildren, value]
+  );
 
-  const flowDisplayValue = hasChildren ? { type: 'constant', schema: { type: ' object' } } : value;
+  console.log('debugger flowDisplayValue', keyName, flowDisplayValue);
```
Comment (xiamidaxia) [inline packages/materials/form-materials/src/components/inputs-values-tree/row.tsx:89]: log 没删

**Review by xiamidaxia — APPROVED** [review]
